BikeManagementSystem/BikeManagementSystem/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BikeManagementSystem.Models;
namespace BikeManagementSystem.Controllers
{
    public class AccessController : Controller
    {
        BIKEMGMTSYSTEMEntities2 db = new BIKEMGMTSYSTEMEntities2();
        // GET: Access
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(User User)
        {
            var user = db.Users.SingleOrDefault(x => x.email == User.email && x.password == User.password);
            if (user != null)
            {
                Session["userId"] = user.idUsers;
                Session["name"] = user.name;
                Session["email"] = user.email;
                Session["image"] = Convert.ToBase64String(user.photo);
                string roleName =db.Rols
                   .Where(r => r.idRol == user.idRol)
                   .Select(r => r.description)
                   .FirstOrDefault();
                Session["varRoleName"] = roleName;
                if(roleName == "Admin")
                {
                    return RedirectToAction("DashBoard", "Admin");
                }
                else
                {
                    return RedirectToAction("NewOrder", "Order");
                }
            }
            ViewBag.InvalidCredential = "Invalid Email or Password";
            return View();
        }

        [HttpGet]
        public ActionResult NewRegistration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewRegistration(User user, HttpPostedFileBase frontCnic, HttpPostedFileBase backCnic, HttpPostedFileBase imgFile)
        {
            try
            {
                user.idRol = 2;
                user.isActive = true;
                if (frontCnic != null) 
                {
                    user.cnicFront = ConvertImage(frontCnic);
                }
                if (backCnic != null)
                {
                    user.cnicBack = ConvertImage(backCnic);
                }
                if (frontCnic != null)
                {
                    user.photo = ConvertImage(imgFile);
                }
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Login");
            }
            catch (Exception)
            {
                ViewBag.Error("Error in registring user!!");
                throw;
            }
        }
        byte[] ConvertImage(HttpPostedFileBase imgFile)
        {
            byte[] imageData = new byte[0];
            using (var binaryReader = new BinaryReader(imgFile.InputStream))
            {
                imageData = binaryReader.ReadBytes(imgFile.ContentLength);
            }
            return imageData;
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            Session.RemoveAll();
            return RedirectToAction("Login");
        }
    }
}

BikeManagementSystem/BikeManagementSystem/Views/Access/Login.cshtml
@model BikeManagementSystem.Models.User

@{
    ViewBag.Title = "Login";
    Layout = null;
}



<!-- Mirrored from dompet.dexignlab.com/xhtml/page-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 13 Jun 2021 12:07:22 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Dompet : Payment Admin Template" />
    <meta property="og:title" content="Dompet : Payment Admin Template" />
    <meta property="og:description" content="Dompet : Payment Admin Template" />
    <meta property="og:image" content="social-image.png" />
    <meta name="format-detection" content="telephone=no">

    <!-- PAGE TITLE HERE -->
    <title>Dompet : Payment Admin Template</title>

    <!-- FAVICONS ICON -->
    <link rel="shortcut icon" type="image/png" href="~/Assets/images/favicon.png" />
    <link href="~/Assets/css/style.css" rel="stylesheet">

</head>

<body class="vh-100">

    @using (Html.BeginForm("Login", "Access", FormMethod.Post))
    {
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-6">
                        @if (ViewBag.InvalidCredential != null)
                        {
                            <div class="alert alert-danger" role="alert">
                                @ViewBag.InvalidCredential
                            </div>
                        }
                        <div class="authincation-content">
                            <div class="row no-gutters">
                                <div class="col-xl-12">
                                    <div class="auth-form">
                                        <div class="text-center mb-3">
                                            @*<a href="~/Assets/index.html"><img src="~/Assets/images/logo-full.png" alt=""></a>*@
                                            <h1>BRMS</h1>
                                        </div>
                                        <h4 class="text-center mb-4">Sign in your account</h4>
                                        <form action="">
                                            <div class="mb-3">
                                                <label class="mb-1"><strong>Email</strong></label>
                                                @Html.TextBoxFor(model => model.email, htmlAttributes: new { @class = "form-control", type = "email", placeholder = "Email" })
                                                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                            </div>
                                            <div class="mb-3">
                                                <label class="mb-1"><strong>Password</strong></label>
                                                @Html.TextBoxFor(model => model.password, htmlAttributes: new { @class = "form-control", type = "password", placeholder = "Password" })
                                                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                                            </div>
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-primary btn-block">Sign Me In</button>
                                            </div>
                                            <div class="text-center mt-3">
                                                <a href="@Url.Action("NewRegistration","Access")" class="btn btn-link">New Registration</a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="~/Assets/vendor/global/global.min.js"></script>
    <script src="~/Assets/js/custom.min.js"></script>
    @*<script src="~/Assets/js/dlabnav-init.js"></script>
        <script src="~/Assets/js/styleSwitcher.js"></script>*@
</body>

BikeManagementSystem/BikeManagementSystem/Views/Access/NewRegistration.cshtml
@model BikeManagementSystem.Models.User
@{
    ViewBag.Title = "NewRegistration";
    Layout = null;
}


<!-- Mirrored from dompet.dexignlab.com/xhtml/page-login.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 13 Jun 2021 12:07:22 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <meta name="robots" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Dompet : Payment Admin Template" />
    <meta property="og:title" content="Dompet : Payment Admin Template" />
    <meta property="og:description" content="Dompet : Payment Admin Template" />
    <meta property="og:image" content="social-image.png" />
    <meta name="format-detection" content="telephone=no">

    <!-- PAGE TITLE HERE -->
    <title>Dompet : Payment Admin Template</title>

    <!-- FAVICONS ICON -->
    <link rel="shortcut icon" type="image/png" href="~/Assets/images/favicon.png" />
    <link href="~/Assets/css/style.css" rel="stylesheet">

</head>

<body class="vh-100">

    @using (Html.BeginForm("NewRegistration", "Access", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-6">
                        <div class="authincation-content">
                            @if (ViewBag.Error != null)
                            {
                                <div class="alert alert-danger" role="alert">
                                    ViewBag.Error
                                </div>
                            }
                            <div class="row no-gutters">
                                <div class="col-xl-12">
                                    <div class="auth-form">
                                        <div class="text-center mb-3">
                                            @*<a href="~/Assets/index.html"><img src="~/Assets/images/logo-full.png" alt=""></a>*@
                                            <h1>BRMS</h1>
                                        </div>
                                        <h4 class="text-center mb-4">Sign Up your account</h4>
                                        <form>
                                            <div class="row">
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Name</label>
                                                    @Html.TextBoxFor(model => model.name, htmlAttributes: new { @class = "form-control", type = "text", placeholder = "John" })
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Email</label>
                                                    @Html.TextBoxFor(model => model.email, htmlAttributes: new { @class = "form-control", type = "email", placeholder = "Email" })
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Phone</label>
                                                    @Html.TextBoxFor(model => model.phone, htmlAttributes: new { @class = "form-control", type = "number", placeholder = "1234" })
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Password</label>
                                                    @Html.TextBoxFor(model => model.password, htmlAttributes: new { @class = "form-control", type = "Password" })
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Front CNIC</label>
                                                    <input type="file" class="form-control" name="frontCnic" />
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">Back CNIC</label>
                                                    <input type="file" class="form-control" name="backCnic" />
                                                </div>
                                                <div class="mb-3 col-md-6">
                                                    <label class="form-label">University Card</label>
                                                    <input type="file" class="form-control" name="imgFile" />
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Save</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }


    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
    <script src="~/Assets/vendor/global/global.min.js"></script>
    <script src="~/Assets/js/custom.min.js"></script>
    @*<script src="~/Assets/js/dlabnav-init.js"></script>
        <script src="~/Assets/js/styleSwitcher.js"></script>*@
</body>